[package]
name    = "velox-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
v8             = { workspace = true }
tokio          = { workspace = true }
log            = { workspace = true }
thiserror      = { workspace = true }
anyhow         = { workspace = true }
velox-security = { path = "../velox-security" }
velox-db       = { path = "../velox-db" }
serde_json     = { workspace = true }
rfd                 = { workspace = true }
arboard             = { workspace = true }
clipboard-win       = { workspace = true }
notify-rust         = { workspace = true }
raw-window-handle   = { workspace = true }
reqwest             = { workspace = true }
base64              = { workspace = true }
tokio-tungstenite   = { workspace = true }
futures-util        = { workspace = true }
mdns-sd             = { workspace = true }
velox-perf          = { path = "../velox-perf" }
velox-sysapi        = { path = "../velox-sysapi" }
battery             = { workspace = true }
sysinfo             = { workspace = true }
keepawake           = { workspace = true }
gilrs               = { workspace = true }
global-hotkey       = { workspace = true }
rodio               = { workspace = true }
serde               = { workspace = true }
velox-3d            = { path = "../velox-3d" }
velox-ai            = { path = "../velox-ai" }

[features]
default = ["v8"]
v8 = []       # V8 backend (current only backend; rusty_v8 dep is always required for now)
dev = []      # dev overlay, hot-reload, CDP inspector
# jsc = []    # future: JavaScriptCore (iOS/macOS)
# quickjs = [] # future: QuickJS (embedded/WASM)
