[package]
name    = "glyx-sysapi"
version = "0.1.0"
edition = "2021"

[dependencies]
battery    = { workspace = true }
sysinfo    = { workspace = true }
keepawake  = { workspace = true }
dark-light = { workspace = true }
keyring    = { workspace = true }
nokhwa     = { workspace = true }
cpal       = { workspace = true }
hound      = { workspace = true }
log        = { workspace = true }
