//! Integrity verification for the glyx-media DLL.
//!
//! Two layers:
//!  1. Ed25519 signature on the manifest JSON (prevents tampered manifests).
//!  2. SHA-256 hash of the DLL bytes (prevents CDN/cache corruption).
//!
//! The Ed25519 public key is compiled into this crate at build time — it is NOT
//! a file on disk that can be replaced by an attacker.

use sha2::{Digest, Sha256};
use std::path::Path;

/// The Ed25519 public key compiled into glyx-runner at build time.
/// Replace with the real 32-byte key generated by CI before shipping.
const PUBKEY: &[u8; 32] = include_bytes!("../keys/glyx_media_verify.pub");

#[derive(serde::Deserialize)]
pub struct Manifest {
    pub version: String,
    pub url:     String,
    pub sha256:  String,    // lowercase hex
    /// The FFmpeg runtime libraries that must sit beside the DLL, by file
    /// name, with their SHA-256. Covered by the manifest signature, so a
    /// swapped library is refused like a swapped DLL. Empty for manifests
    /// written before this field existed (nothing to check).
    #[serde(default)]
    pub libs: std::collections::BTreeMap<String, String>,
    /// The release archive that holds `libs`, so they can be downloaded.
    #[serde(default)]
    pub ffmpeg_archive: Option<ArchiveRef>,
}

/// A downloadable file named in the manifest.
#[derive(serde::Deserialize, Clone)]
pub struct ArchiveRef {
    pub name:   String,
    pub sha256: String,
}

/// A file name that is safe to join onto a directory: not empty, no path
/// separators, no `..`, no drive or stream marker.
pub fn is_plain_file_name(name: &str) -> bool {
    !name.is_empty()
        && name != "."
        && name != ".."
        && !name.contains(['/', '\\', ':', '\0'])
}

/// SHA-256 of a file, read in chunks so a large library isn't held in memory.
pub fn sha256_file(path: &Path) -> Result<String, String> {
    use std::io::Read;
    let mut f = std::fs::File::open(path).map_err(|e| format!("cannot open {}: {e}", path.display()))?;
    let mut h = Sha256::new();
    let mut buf = vec![0u8; 64 * 1024];
    loop {
        let n = f.read(&mut buf).map_err(|e| format!("cannot read {}: {e}", path.display()))?;
        if n == 0 { break; }
        h.update(&buf[..n]);
    }
    Ok(format!("{:x}", h.finalize()))
}

/// Check every library the manifest lists against the files in `dir`.
pub fn verify_libs(dir: &Path, libs: &std::collections::BTreeMap<String, String>) -> Result<(), String> {
    for (name, want) in libs {
        if !is_plain_file_name(name) {
            return Err(format!("glyx-media: the manifest lists an unsafe library name {name:?}"));
        }
        let got = sha256_file(&dir.join(name))
            .map_err(|e| format!("glyx-media: FFmpeg library {name}: {e}"))?;
        if !got.eq_ignore_ascii_case(want) {
            return Err(format!(
                "glyx-media: FFmpeg library {name} does not match the signed manifest \
                 (expected {want}, got {got}); re-download it"
            ));
        }
    }
    Ok(())
}

/// Compute SHA-256 of `data` and return lowercase hex string.
pub fn sha256_hex(data: &[u8]) -> String {
    let mut h = Sha256::new();
    h.update(data);
    format!("{:x}", h.finalize())
}

/// Returns `true` when signature verification should be skipped.
///
/// Two cases:
///  1. `GLYX_MEDIA_SKIP_VERIFY=1` env var — explicit dev override.
///  2. Debug build (`cfg!(debug_assertions)`) — allows locally-built DLLs with
///     stub signatures when developing without a CI signing key.
///
/// **Never** skip in release builds without the env var.
fn skip_verify() -> bool {
    #[cfg(debug_assertions)]
    {
        if std::env::var("GLYX_MEDIA_SKIP_VERIFY").as_deref() == Ok("1") {
            log::warn!("[glyx-media] GLYX_MEDIA_SKIP_VERIFY=1 — Ed25519 check bypassed (dev only)");
            return true;
        }
        log::debug!("[glyx-media] debug build — Ed25519 verification skipped");
        return true;
    }
    #[cfg(not(debug_assertions))]
    false
}

/// Verify the Ed25519 signature on a manifest.
/// Returns the parsed `Manifest` on success.
///
/// When `GLYX_MEDIA_SKIP_VERIFY=1` only the JSON parse is checked — the
/// signature is not verified.  Use this flag only during local development
/// with DLLs built by `glyx-media-c/build-windows.ps1`.
pub fn verify_manifest(manifest_bytes: &[u8], sig_bytes: &[u8]) -> Result<Manifest, String> {
    if !skip_verify() {
        use ed25519_dalek::{Signature, Verifier, VerifyingKey};

        let vk = VerifyingKey::from_bytes(PUBKEY)
            .map_err(|e| format!("glyx-media: invalid public key: {e}"))?;

        let sig_arr: [u8; 64] = sig_bytes
            .try_into()
            .map_err(|_| "glyx-media: signature must be 64 bytes".to_string())?;
        let sig = Signature::from_bytes(&sig_arr);

        vk.verify(manifest_bytes, &sig)
            .map_err(|_| "glyx-media: manifest Ed25519 signature invalid".to_string())?;
    } else {
        log::warn!("[glyx-media] GLYX_MEDIA_SKIP_VERIFY=1 — Ed25519 check bypassed (dev only)");
    }

    // Strip UTF-8 BOM if present (PowerShell 5.1 Set-Content writes one).
    let json = if manifest_bytes.starts_with(b"\xEF\xBB\xBF") {
        &manifest_bytes[3..]
    } else {
        manifest_bytes
    };
    serde_json::from_slice(json)
        .map_err(|e| format!("glyx-media: manifest JSON parse error: {e}"))
}

/// Verify a cached DLL against its sidecar manifest + signature files.
///
/// Returns an open `std::fs::File` handle to the DLL on success.  The
/// caller MUST keep this handle open until `Library::new` / `dlopen`
/// returns — holding the handle prevents file replacement on Windows
/// (mandatory locking) and shrinks the TOCTOU window to sub-millisecond
/// on Unix.
///
/// On hash mismatch the DLL file is deleted so it will be re-downloaded.
pub fn verify_cached_dll(dll_path: &Path) -> Result<std::fs::File, String> {
    use std::io::Read;

    let manifest_path = dll_path.with_extension("manifest.json");
    let sig_path      = dll_path.with_extension("manifest.sig");

    // No manifest sidecar: deny in release; allow in debug.
    if !manifest_path.exists() {
        #[cfg(not(debug_assertions))]
        {
            return Err(format!(
                "glyx-media: no manifest at {} -- refusing to load unsigned DLL in release build",
                manifest_path.display()
            ));
        }
        #[cfg(debug_assertions)]
        {
            log::warn!(
                "[glyx-media] no manifest for {} -- skipping verification (debug build only)",
                dll_path.display()
            );
            // Return an open handle even in the no-verify path so the call
            // site is uniform and still holds a handle across dlopen.
            return std::fs::File::open(dll_path)
                .map_err(|e| format!("glyx-media: cannot open DLL: {e}"));
        }
    }

    let manifest_bytes = std::fs::read(&manifest_path)
        .map_err(|_| format!("glyx-media: missing manifest at {}", manifest_path.display()))?;
    let sig_bytes = std::fs::read(&sig_path)
        .map_err(|_| format!("glyx-media: missing signature at {}", sig_path.display()))?;

    let manifest = verify_manifest(&manifest_bytes, &sig_bytes)?;

    // R4: open the file ONCE, read bytes for hashing, keep the handle open.
    // On Windows this holds a shared-read lock preventing replacement.
    // On Unix it closes the TOCTOU window to near-zero.
    let mut dll_file = std::fs::File::open(dll_path)
        .map_err(|e| format!("glyx-media: cannot open DLL: {e}"))?;
    let mut dll_bytes = Vec::new();
    dll_file.read_to_end(&mut dll_bytes)
        .map_err(|e| format!("glyx-media: cannot read DLL: {e}"))?;

    let actual_hash = sha256_hex(&dll_bytes);
    if actual_hash != manifest.sha256 {
        drop(dll_file);
        let _ = std::fs::remove_file(dll_path);
        return Err(format!(
            "glyx-media: SHA-256 mismatch (expected {}, got {}) -- cached DLL deleted, re-download required",
            manifest.sha256, actual_hash
        ));
    }

    // The FFmpeg libraries the DLL loads from beside itself are part of what
    // the signature vouches for. (They can't be held open across the load the
    // way the DLL is, so a replacement in that instant isn't covered.)
    verify_libs(dll_path.parent().unwrap_or_else(|| Path::new(".")), &manifest.libs)?;

    // Return the still-open handle so the caller can hold it across dlopen.
    Ok(dll_file)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;

    fn temp_dir(tag: &str) -> std::path::PathBuf {
        let d = std::env::temp_dir().join(format!("glyx-media-verify-{tag}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&d);
        std::fs::create_dir_all(&d).unwrap();
        d
    }

    #[test]
    fn old_manifests_without_libs_still_parse() {
        let m: Manifest = serde_json::from_str(r#"{"version":"1.0.0","url":"u","sha256":"ab"}"#).unwrap();
        assert!(m.libs.is_empty() && m.ffmpeg_archive.is_none());
    }

    #[test]
    fn manifests_list_libs_and_their_archive() {
        let m: Manifest = serde_json::from_str(
            r#"{"version":"0.2.0","url":"u","sha256":"ab",
                "libs":{"avcodec-63.dll":"aa"},
                "ffmpeg_archive":{"name":"glyx-ffmpeg-libs.tar.gz","sha256":"bb"}}"#).unwrap();
        assert_eq!(m.libs["avcodec-63.dll"], "aa");
        assert_eq!(m.ffmpeg_archive.unwrap().name, "glyx-ffmpeg-libs.tar.gz");
    }

    #[test]
    fn plain_file_names_only() {
        for ok in ["avcodec-63.dll", "libavcodec.63.dylib", "libavutil.so.61"] { assert!(is_plain_file_name(ok), "{ok}"); }
        for bad in ["", ".", "..", "a/b", "..\\x", "../x", "c:evil", "a\0b"] { assert!(!is_plain_file_name(bad), "{bad:?}"); }
    }

    #[test]
    fn libs_must_match_the_manifest() {
        let dir = temp_dir("match");
        std::fs::write(dir.join("a.dll"), b"hello").unwrap();
        let good = sha256_hex(b"hello");
        let libs = BTreeMap::from([("a.dll".to_string(), good.clone())]);
        assert!(verify_libs(&dir, &libs).is_ok());

        // a swapped library
        std::fs::write(dir.join("a.dll"), b"evil").unwrap();
        let err = verify_libs(&dir, &libs).unwrap_err();
        assert!(err.contains("a.dll") && err.contains("does not match"), "{err}");

        // a missing one
        let libs = BTreeMap::from([("gone.dll".to_string(), good)]);
        assert!(verify_libs(&dir, &libs).unwrap_err().contains("gone.dll"));

        // an unsafe name never touches the disk
        let libs = BTreeMap::from([("../a.dll".to_string(), "x".to_string())]);
        assert!(verify_libs(&dir, &libs).unwrap_err().contains("unsafe"));
        let _ = std::fs::remove_dir_all(&dir);
    }
}
