//! Integrity verification for the glyx-media DLL.
//!
//! Two layers:
//!  1. Ed25519 signature on the manifest JSON (prevents tampered manifests).
//!  2. SHA-256 hash of the DLL bytes (prevents CDN/cache corruption).
//!
//! The Ed25519 public key is compiled into this crate at build time — it is NOT
//! a file on disk that can be replaced by an attacker.

use sha2::{Digest, Sha256};
use std::path::Path;

/// The Ed25519 public key compiled into glyx-runner at build time.
/// Replace with the real 32-byte key generated by CI before shipping.
const PUBKEY: &[u8; 32] = include_bytes!("../keys/glyx_media_verify.pub");

#[derive(serde::Deserialize)]
pub struct Manifest {
    pub version: String,
    pub url:     String,
    pub sha256:  String,    // lowercase hex
}

/// Compute SHA-256 of `data` and return lowercase hex string.
pub fn sha256_hex(data: &[u8]) -> String {
    let mut h = Sha256::new();
    h.update(data);
    format!("{:x}", h.finalize())
}

/// Returns `true` when signature verification should be skipped.
///
/// Two cases:
///  1. `GLYX_MEDIA_SKIP_VERIFY=1` env var — explicit dev override.
///  2. Debug build (`cfg!(debug_assertions)`) — allows locally-built DLLs with
///     stub signatures when developing without a CI signing key.
///
/// **Never** skip in release builds without the env var.
fn skip_verify() -> bool {
    #[cfg(debug_assertions)]
    {
        if std::env::var("GLYX_MEDIA_SKIP_VERIFY").as_deref() == Ok("1") {
            log::warn!("[glyx-media] GLYX_MEDIA_SKIP_VERIFY=1 — Ed25519 check bypassed (dev only)");
            return true;
        }
        log::debug!("[glyx-media] debug build — Ed25519 verification skipped");
        return true;
    }
    #[cfg(not(debug_assertions))]
    false
}

/// Verify the Ed25519 signature on a manifest.
/// Returns the parsed `Manifest` on success.
///
/// When `GLYX_MEDIA_SKIP_VERIFY=1` only the JSON parse is checked — the
/// signature is not verified.  Use this flag only during local development
/// with DLLs built by `glyx-media-c/build-windows.ps1`.
pub fn verify_manifest(manifest_bytes: &[u8], sig_bytes: &[u8]) -> Result<Manifest, String> {
    if !skip_verify() {
        use ed25519_dalek::{Signature, Verifier, VerifyingKey};

        let vk = VerifyingKey::from_bytes(PUBKEY)
            .map_err(|e| format!("glyx-media: invalid public key: {e}"))?;

        let sig_arr: [u8; 64] = sig_bytes
            .try_into()
            .map_err(|_| "glyx-media: signature must be 64 bytes".to_string())?;
        let sig = Signature::from_bytes(&sig_arr);

        vk.verify(manifest_bytes, &sig)
            .map_err(|_| "glyx-media: manifest Ed25519 signature invalid".to_string())?;
    } else {
        log::warn!("[glyx-media] GLYX_MEDIA_SKIP_VERIFY=1 — Ed25519 check bypassed (dev only)");
    }

    // Strip UTF-8 BOM if present (PowerShell 5.1 Set-Content writes one).
    let json = if manifest_bytes.starts_with(b"\xEF\xBB\xBF") {
        &manifest_bytes[3..]
    } else {
        manifest_bytes
    };
    serde_json::from_slice(json)
        .map_err(|e| format!("glyx-media: manifest JSON parse error: {e}"))
}

/// Verify a cached DLL against its sidecar manifest + signature files.
/// Returns `Ok(())` if the DLL is intact and the manifest is authentic.
/// On hash mismatch the DLL file is deleted so it will be re-downloaded.
///
/// If the manifest sidecar does not exist the DLL was distributed by the
/// installer (not downloaded from CDN), so verification is skipped — the
/// file is already trusted by virtue of the user having run our installer.
pub fn verify_cached_dll(dll_path: &Path) -> Result<(), String> {
    let manifest_path = dll_path.with_extension("manifest.json");
    let sig_path      = dll_path.with_extension("manifest.sig");

    // No manifest sidecar: deny in release (an installer-distributed DLL must
    // ship its manifest); allow in debug (locally-built DLLs have no manifest).
    if !manifest_path.exists() {
        #[cfg(not(debug_assertions))]
        {
            return Err(format!(
                "glyx-media: no manifest at {} — refusing to load unsigned DLL in release build",
                manifest_path.display()
            ));
        }
        #[cfg(debug_assertions)]
        {
            log::warn!(
                "[glyx-media] no manifest for {} — skipping verification (debug build only)",
                dll_path.display()
            );
            return Ok(());
        }
    }

    let manifest_bytes = std::fs::read(&manifest_path)
        .map_err(|_| format!("glyx-media: missing manifest at {}", manifest_path.display()))?;
    let sig_bytes = std::fs::read(&sig_path)
        .map_err(|_| format!("glyx-media: missing signature at {}", sig_path.display()))?;

    let manifest = verify_manifest(&manifest_bytes, &sig_bytes)?;

    let dll_bytes = std::fs::read(dll_path)
        .map_err(|e| format!("glyx-media: cannot read DLL: {e}"))?;
    let actual_hash = sha256_hex(&dll_bytes);

    if actual_hash != manifest.sha256 {
        // Delete corrupted cache — will re-download next launch.
        let _ = std::fs::remove_file(dll_path);
        return Err(format!(
            "glyx-media: SHA-256 mismatch (expected {}, got {}) — cached DLL deleted, re-download required",
            manifest.sha256, actual_hash
        ));
    }

    Ok(())
}
