[package]
name    = "glyx-cap-camera"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
glyx-cap-abi = { path = "../glyx-cap-abi" }
nokhwa       = { version = "0.10", features = ["input-native", "output-threaded"] }
parking_lot  = "0.12"
log          = "0.4"
image        = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
