/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-124557-g9e71ea2d60-20260520"
#endif /* AVUTIL_FFVERSION_H */
