[package]
name    = "velox-db"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx           = { workspace = true }
libsqlite3-sys = { workspace = true }
tokio      = { workspace = true }
log        = { workspace = true }
thiserror  = { workspace = true }
anyhow     = { workspace = true }
serde_json = { workspace = true }
